#!/usr/bin/env bash

# Make sure we are on a cluster with Gold
if /shared/ucl/apps/cluster-bin/whereami &> /dev/null
then
  identifycluster="/shared/ucl/apps/cluster-bin/whereami"
else
  identifycluster="hostname -f"
fi

if "$identifycluster" | grep -q thomas
then
  ssh util04 mybalance -h | column -t
elif "$identifycluster" | grep -q michael
then
  ssh util11 mybalance -h | column -t
elif "$identifycluster" | grep -q myriad
then
  ssh util-ha-nfs mybalance -h | column -t
else 
  echo "There is no resource management on this cluster."
fi
