#!/bin/bash
# Checks the year-based ACLs to see whether a user has reapplied
# for their RC accounts that session.

# use own username if none supplied as argument
username=${1:-$USER}

qconf -su AY201516 | grep -q $username
if [ $? == 0 ]
then
  echo "201516: yes"
else
  echo "201516: no"
fi

qconf -su AY201617 | grep -q $username
if [ $? == 0 ]
then
  echo "201617: yes"
else
  echo "201617: no"
fi

