#!/bin/bash -l
# Checks the year-based ACLs to see whether a user has reapplied
# for their RC accounts that session.

qconf -su AY201516 | grep -q $1
if [ $? == 0 ]
then
  echo "201516: yes"
else
  echo "201516: no"
fi

qconf -su AY201617 | grep -q $1
if [ $? == 0 ]
then
  echo "201617: yes"
else
  echo "201617: no"
fi

