#!/usr/bin/env bash

# v-- gets a list of all directories named .mf_* created more than 7 days ago
dirs_to_remove=`find /shared/ucl/apps -maxdepth 1 -type d -name ".mf_*" -ctime +7`

num_dirs=`echo "$dirs_to_remove" | wc -l`

if [ $num_dirs -eq 0 ]; then
  echo "No directories found." >&2
  exit
fi

while :; do
  read -n 1 -p "This will delete $num_dirs directories. Are you sure you want to continue? [Y|N|(L)ist] " prompt_response

  case "${prompt_response,,*}" in
    "y")
      for i in $dirs_to_remove; do
        if [ ! -a $i/.keep ]; then
          'rm' -vRf $i
        else
          echo "Not deleting $i : .keep file found"
        fi
      exit
      ;;
    "n")
      echo "Okay, doing nothing."
      exit
      ;;
    "l")
      'ls' -lrtd $dirs_to_remove
      ;;
    *)
      echo "Invalid response. Please choose one of y, n, or l."
      ;;
  esac

done

