#!/usr/bin/env bash

# Make sure we are on Thomas

if hostname -A | grep -q thomas
then
  ssh util04 gbalance -h --show Id,Name,Amount,Reserved,Available "$@"
else 
  echo "There is no resource management on this cluster."
fi

