#!/usr/bin/env bash

# Make sure we are on a cluster with Gold

if hostname -A | grep -q thomas
then
  ssh util04 glsalloc -h --show Id,Account,Projects,StartTime,EndTime,Amount,Deposited,Description "$@"
elif hostname -A | grep -q michael
then
  ssh util11 glsalloc -h --show Id,Account,Projects,StartTime,EndTime,Amount,Deposited,Description "$@"
else 
  echo "There is no resource management on this cluster."
fi

