#!/usr/bin/env bash

# Make sure we are on a cluster with Gold

if hostname -A | grep -q thomas
then
  ssh util04 glsuser "$@"
elif hostname -A | grep -q michael
then
  ssh util11 glsuser "$@"
else 
  echo "There is no resource management on this cluster."
fi

