#!/usr/bin/env bash

# Generate and output sha256sums in the same format as iRODs uses.
# https://docs.irods.org/4.2.0/system_overview/tips_and_tricks/

if [ -n "$1" ]; then
  for file in "$@" 
  do
    sum=$(sha256sum "$file" | xxd -r -p | base64)
    echo "sha2:$sum  $file"
  done
else
  echo "Usage: $0 [file 1] [file 2] ..."
  exit -1
fi
