#!/usr/bin/env bash

FoundAll="y"

if declare -f module 2>/dev/null >/dev/null; then
  LoadedModules=$(module -t list 2>&1)
  LoadedModules=${LoadedModules#*:}
else
  echo "No module function found -- is a module environment being used?" >&2
  exit 2
fi

while [ -n "$1" ]; do
  LookFor="$1"

  Found="n"
  TargetLen=${#LookFor}
  let TargetLen=$(( TargetLen + 1 ))
  for line in $LoadedModules; do
    line="$line/"
    if [ "$LookFor/" = "${line:0:${TargetLen}}" ]; then
      Found="y"
    fi
  done
  if [ "$Found" = "n" ]; then
    FoundAll="n"
  fi
  shift
done

if [ "$FoundAll" = "y" ]; then
  exit 0
else
  exit 1
fi
