#!/usr/bin/env bash

# The q stands for quick as well as queue - this might not be too reliable:

if [[ -z "$1" ]]; then
  echo "Error: No job id provided." >&2
  exit 5
fi

if [[ "$1" == "--help" ]]; then
  echo -e "Usage: qexplain \e[04mjob_id\e[00m\n"
  echo " Prints the cause of the error state in a job."
  exit
fi

while [[ -n "$1" ]]; do
  # First qstat call is for error messages, otherwise you get them in XML format
  qstat -j "$1" >/dev/null \
      && echo -n "Job ID: $1 --" \
      && qstat -j "$1" -xml \
          | grep QIM_message \
          | perl -MHTML::Entities -pe 'decode_entities($_); $_ =~ s/<.*?>//g; $_ =~ s/ +/ /g;'
  shift
done

