#!/bin/bash 
# wrapper for python3 thomas script

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

module load gcc-libs
module load python3/3.5
module load mysql-connector-python/2.0.4

./thomas/thomas-show "$@"

