#!/usr/bin/env bash

E_DOESNOTEXIST=2
E_UNKNOWNSOURCE=4
E_NOTYOURS=5
E_NOTTHOSEFILES=6
E_FAILEDREADLINK=7

current_host=`hostname -f`
current_host_stem="${current_host#*.}"

case "${current_host_stem}" in
  "data.legion.ucl.ac.uk")
    target_host="login01.ext.grace.ucl.ac.uk"
    ;;
  "grace.ucl.ac.uk")
    target_host="login05.external.legion.ucl.ac.uk"
    ;;
  *)
    echo -e "This script does not know where it is.\n It is panicking, like a lost kitten. \n It only knows it is at a host with DNS suffix: ${current_host_stem}" >&2
    exit $E_UNKNOWNSOURCE
    ;;
esac

for source in "$@"; do
  if [ ! -e "$source" ]; then
    echo "File or directory does not exist: $source" >&2
    exit $E_DOESNOTEXIST
  fi

  source_path=`readlink -e "$source"`

  if [ $? -ne 0 ]; then
    echo "Could not determine full path of file: $source" >&2
    exit $E_FAILEDREADLINK
  fi

  # Check owner of target
  owner=`stat -c%U "$source_path"`
  current_user=`whoami`

  if [ "$owner" != "$current_user" ]; then
    echo "This script will not operate on files you do not own." >&2
    exit $E_NOTYOURS
  fi


  echo "Trying to transfer: ${source_path}" >&2
  case "${source_path}" in
    /imports/iridis/*)
      tar -cz ${source_path} | ssh -t "$target_host" tar -xvz --xform="simports/iridis/${current_user}/iridis_import/"
      # ^-- So, if you send over your iridis files, they'll end up in
      #  ~/iridis_imports
      # which isn't ideal but isn't the worst either
      #
      # At least I hope that's what'll happen
      # Tar strips the leading / automatically
      ;;
    /home/${current_user}/*|/imports/home?/${current_user}/*|/scratch/scratch/${current_user}/*)
      tar -cz ${source_path} | ssh -t "$target_host" tar -xvz --xform="simports/home./${current_user}/./"
     # ^-- I was going to use rsync here but the /imports/home? link messed that up 
      #rsync -a --stats -r --relative "$source_path" "$target_host":"$target_relative"
      ;;
    *)
      echo "This script will not operate on files outside your home or Scratch area." >&2
      exit $E_NOTTHOSEFILES
      ;;
  esac

done 
