#!/bin/bash
# Very non-exhaustive tests for ${cluster}-show

cluster="$1"
if [[ -z "$cluster" ]]; then
  echo "Usage: $0 <cluster>" >&2
  exit 1
fi

cluster_show="./${cluster}-show"
if [[ ! -x "${cluster_show}" ]]; then
  echo "script '${cluster_show}' not found or not executable" >&2
  exit 1
fi

# generate random number between 1 and 145 ($RANDOM starts at 0)
range=144
number=$(( RANDOM % range +1 ))
# pad to 4 digits
printf -v number "%04d" $number

echo "------ Test show mmm user"
"${cluster_show}" --user "mmm$number"

echo ""
echo "------ Test show contacts"
"${cluster_show}" --contacts

echo ""
echo "------ Test show institutes"
"${cluster_show}" --institutes

echo ""
echo "------ Test show allusers"
"${cluster_show}" --allusers

echo ""
echo "------ Test show getmmm"
"${cluster_show}" --getmmm

echo ""
echo "------ Test show recentusers (default 5)"
"${cluster_show}" recentusers

echo ""
echo "------ Test show 8 recentusers"
"${cluster_show}" recentusers -n 8

echo ""
echo "------ Test getusers in Soton"
"${cluster_show}" getusers -i Soton

echo ""
echo "------ Test getusers in Soton that were in the pilot"
"${cluster_show}" getusers -i Soton -p Soton_pilot

echo ""
echo "------ Test whois - containing ucl in email address"
"${cluster_show}" whois -e ucl

echo ""
echo "------ Test requests (default)"
"${cluster_show}" requests

echo ""
echo "------ Test requests pending"
"${cluster_show}" requests --pending

echo ""
echo "------ Test requests all"
"${cluster_show}" requests --all

echo ""
echo "------ Test requests recent (default 5)"
"${cluster_show}" requests recent

echo ""
echo "------ Test requests recent 8"
"${cluster_show}" requests recent -n 8


